language: go
go:
  - 1.10.x
  - master

before_install:
  # Setup dependency management tool
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

install:
  - dep ensure

deploy:
- provider: script
  skip_cleanup: true
  script: make stage
